### ISSUE TITLE
Error in Plugin...

### ISSUE THREAD

**Issue by amityk77** [atlascoder/tracker_hider#17]
Hello,

Recently I am getting errors while clicking in "Summary" link of Redmine project.

Following are the details of my system followed by the error log:

Environment:
  Redmine version         3.3.0.stable
  Ruby version               2.3.1-p112 (2016-04-26) [x86_64-linux]
  Rails version                4.2.6
  Environment               production
  Database adapter       Mysql2

--------------------------------------------------------------------------------

Error log:
/var/www/html/redmine330/plugins/tracker_hider/lib/tracker_hider_project_patch.rb:11:in `rolled_up_trackers'
/var/www/html/redmine330/app/controllers/reports_controller.rb:23:in `issue_report'
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/abstract_controller/base.rb:198:in `process_action'
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/rendering.rb:10:in `process_action'
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:117:in `call'
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:505:in `call'
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
/var/www/html/redmine330/lib/redmine/sudo_mode.rb:63:in `sudo_mode'
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:432:in `block in make_lambda'
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:312:in `block in halting'
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:497:in `block in around'
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:505:in `call'
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/abstract_controller/callbacks.rb:19:in `process_action'
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/rescue.rb:29:in `process_action'
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `block in instrument'
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `instrument'
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/usr/lib64/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/abstract_controller/base.rb:137:in `process'
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/rendering.rb:30:in `process'
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal.rb:196:in `dispatch'
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal.rb:237:in `block in action'
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:43:in `serve'
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/router.rb:30:in `each'
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/router.rb:30:in `serve'
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:817:in `call'
/usr/lib64/ruby/gems/2.3.0/gems/rack-openid-1.4.2/lib/rack/openid.rb:98:in `call'
/usr/lib64/ruby/gems/2.3.0/gems/request_store-1.0.5/lib/request_store/middleware.rb:9:in `call'
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:25:in `call'
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-xml_parser-1.0.2/lib/action_dispatch/xml_params_parser.rb:16:in `call'
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/flash.rb:260:in `call'
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/usr/lib64/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/query_cache.rb:36:in `call'
/usr/lib64/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/usr/lib64/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/rack/logger.rb:38:in `call_app'
/usr/lib64/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/rack/logger.rb:20:in `block in call'
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:26:in `tagged'
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:68:in `tagged'
/usr/lib64/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/rack/logger.rb:20:in `call'
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/static.rb:120:in `call'
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
/usr/lib64/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:518:in `call'
/usr/lib64/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/application.rb:165:in `call'
/usr/lib64/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/railtie.rb:194:in `public_send'
/usr/lib64/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/railtie.rb:194:in `method_missing'
/usr/lib64/ruby/gems/2.3.0/gems/passenger-5.0.28/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
/usr/lib64/ruby/gems/2.3.0/gems/passenger-5.0.28/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
/usr/lib64/ruby/gems/2.3.0/gems/passenger-5.0.28/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
/usr/lib64/ruby/gems/2.3.0/gems/passenger-5.0.28/src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
/usr/lib64/ruby/gems/2.3.0/gems/passenger-5.0.28/src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'

**Comment by atlascoder** [comment]
Hi, thanks for this report! Probably it is actual for Redmine from 3.3, I will consider.
By the way, have you tried similar settings for roles in admin mode?
![image](https://cloud.githubusercontent.com/assets/9552354/20452701/4013fd7c-ae19-11e6-8112-738bb8d735d2.png)

It must be that this is new core feature does the same functionality and the plugin is not needed more.
