### ISSUE TITLE
error with global_role branch

### ISSUE THREAD

**Issue by quanvn** [atlascoder/tracker_hider#5]
I got this error when using global role branch (master branch works fine)

Started GET "/redmine/projects/test/issues" for 10.1.13.112 at 2015-11-18 10:53:00 +0700
Processing by IssuesController#index as HTML
  Parameters: {"project_id"=>"test"}
  Current user: quan.ltt (id=3)
Completed 500 Internal Server Error in 29.4ms

ActiveRecord::StatementInvalid (Mysql2::Error: Unknown column 'members.user' in 'where clause': SELECT `members`.`id` AS t0_r0, `members`.`user_id` AS t0_r1, `members`.`project_id` AS t0_r2, `members`.`created_on` AS t0_r3, `members`.`mail_notification` AS t0_r4, `members`.`dmsf_mail_notification` AS t0_r5, `users`.`id` AS t1_r0, `users`.`login` AS t1_r1, `users`.`hashed_password` AS t1_r2, `users`.`firstname` AS t1_r3, `users`.`lastname` AS t1_r4, `users`.`mail` AS t1_r5, `users`.`admin` AS t1_r6, `users`.`status` AS t1_r7, `users`.`last_login_on` AS t1_r8, `users`.`language` AS t1_r9, `users`.`auth_source_id` AS t1_r10, `users`.`created_on` AS t1_r11, `users`.`updated_on` AS t1_r12, `users`.`type` AS t1_r13, `users`.`identity_url` AS t1_r14, `users`.`mail_notification` AS t1_r15, `users`.`salt` AS t1_r16, `users`.`must_change_passwd` AS t1_r17, `users`.`passwd_changed_on` AS t1_r18, `users`.`reminder_notification` AS t1_r19, `users`.`app_notification` AS t1_r20, `users`.`app_notification_desktop` AS t1_r21, `roles`.`id` AS t2_r0, `roles`.`name` AS t2_r1, `roles`.`position` AS t2_r2, `roles`.`assignable` AS t2_r3, `roles`.`builtin` AS t2_r4, `roles`.`permissions` AS t2_r5, `roles`.`issues_visibility` AS t2_r6 FROM `members` LEFT OUTER JOIN `users` ON `users`.`id` = `members`.`user_id` LEFT OUTER JOIN `member_roles` ON `member_roles`.`member_id` = `members`.`id` LEFT OUTER JOIN `roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `members`.`project_id` = 86 AND `members`.`user` = 3 AND (users.type='User' AND users.status=1)):
  app/models/query.rb:300:in `trackers'
  app/models/issue_query.rb:168:in `initialize_available_filters'
  app/models/query.rb:355:in `available_filters'
  app/models/query.rb:244:in `build_from_params'
  app/models/issue_query.rb:119:in `build_from_params'
  app/helpers/queries_helper.rb:185:in `retrieve_query'
  app/controllers/issues_controller.rb:56:in `index'

**Comment by atlascoder** [comment]
quanvn, thanks!
